### ISSUE TITLE
参考文献自动补全

### ISSUE THREAD

**Issue by sqiangcao99** [lcpu-club/overleaf#18]
overleaf 支持引用的自动补全，会考虑支持吗?
![image](https://github.com/user-attachments/assets/7351b0ec-1360-4884-912c-ed258e22fd7b)

**Comment by HolgerHuo** [comment]
latex.pku.edu.cn 中是已经支持了的，请问有哪个文档没有支持这个功能吗？
![image](https://github.com/user-attachments/assets/168e9670-0392-4037-ab2d-b2e77fb15ab6)

**Comment by HolgerHuo** [comment]
#17 具体可以参见这个PR

**Comment by sqiangcao99** [comment]
谢谢。之前我拉取的镜像是`ghcr.io/lcpu-club/sharelatex:latest`, 更换成`ghcr.io/lcpu-club/sharelatex:sha-9964aeb`之后就可以了。

**Comment by HolgerHuo** [comment]
> @HolgerHuo lastest标签重新打一下？
收到，在这里更新了 https://github.com/lcpu-club/overleaf/actions/runs/12355440776

> 谢谢。之前我拉取的镜像是ghcr.io/lcpu-club/sharelatex:latest, 更换成ghcr.io/lcpu-club/sharelatex:sha-9964aeb之后就可以了。
没事的，latest标签对应最新的git `tag`，有些commit和pr可能没来及合并进来。我近期会完善一下文档说明docker镜像的tag规则并跟进上游更新。
